openapi: 3.0.2
info:
  title: Banklo - Acquirer APIs
  version: 1.0.0
  description: A brand new API with no content.  Go nuts!
paths:
  /transactions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-transaction'
        required: true
      tags:
        - transactions
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/401-unauthorized'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: create-transaction
  '/transactions/{id}/cancellation':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-cancellation'
        required: true
      tags:
        - transactions
      parameters:
        -
          name: id
          description: transaction id to apply operation
          schema:
            type: string
          in: path
          required: true
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/403-forbidden'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: request-cancellation
  '/transactions/{id}/reversal':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-reversal'
        required: true
      tags:
        - transactions
      parameters:
        -
          name: id
          description: transaction id to apply operation
          schema:
            type: string
          in: path
          required: true
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/403-forbidden'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: request-reversal
components:
  schemas:
    id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      minLength: 36
      maxLength: 36
      example: 4cb0b69e-e4bd-46f6-b011-8cd5d2d3964b
    currency_code:
      type: string
      minLength: 3
      maxLength: 3
      example: EUR
      description: |
        The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
    country_code:
      type: string
      description: |
        The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
      minLength: 3
      maxLength: 3
      example: ARG
    request-transaction:
      title: request-transaction
      description: ''
      required:
        - transaction_data
        - authorization_code
        - acquirer_code
        - merchant_code
        - currency_code
        - country_code
        - product_id
        - pos_id
      type: object
      properties:
        authorization_code:
          type: string
        acquirer_code:
          type: string
        merchant_code:
          type: string
        currency_code:
          $ref: '#/components/schemas/currency_code'
        transaction_data:
          $ref: '#/components/schemas/transaction-data-request'
        country_code:
          $ref: '#/components/schemas/country_code'
        product_id:
          $ref: '#/components/schemas/id'
        pos_id:
          $ref: '#/components/schemas/id'
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: EUR
        transaction_data:
          with_password: true
          operation: credit
          amount: 231
          transaction_id: a225edb0-0c03-11ed-ae03-c3d8f097c2ff
          card_id: faaeca61-3300-11ed-a86f-d45d64b317ef
        country_code: BRA
        product_id: b7679b5c-0c02-11ed-8716-0b78014761cd
        pos_id: a225ed74-0c03-11ed-ae01-630c1a4b2fbc
    request-reversal:
      title: request-reversal
      description: ''
      required:
        - transaction_data
        - authorization_code
        - acquirer_code
        - country_code
        - currency_code
        - product_id
        - pos_id
      type: object
      properties:
        authorization_code:
          type: string
        acquirer_code:
          type: string
        merchant_code:
          type: string
        currency_code:
          $ref: '#/components/schemas/currency_code'
        transaction_data:
          $ref: '#/components/schemas/transaction-data-request'
        country_code:
          $ref: '#/components/schemas/country_code'
        product_id:
          $ref: '#/components/schemas/id'
        pos_id:
          $ref: '#/components/schemas/id'
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: EUR
        transaction_data:
          transaction_id: a225edb0-0c03-11ed-ae03-c3d8f097c2ff
        country_code: BRA
        product_id: b7679b5c-0c02-11ed-8716-0b78014761cd
        pos_id: a225ed74-0c03-11ed-ae01-630c1a4b2fbc
    request-cancellation:
      title: request-cancellation
      description: ''
      required:
        - transaction_data
        - authorization_code
        - acquirer_code
        - merchant_code
        - currency_code
        - country_code
        - product_id
        - pos_id
      type: object
      properties:
        authorization_code:
          type: string
        acquirer_code:
          type: string
        merchant_code:
          type: string
        currency_code:
          $ref: '#/components/schemas/currency_code'
        transaction_data:
          $ref: '#/components/schemas/transaction-data-request'
        country_code:
          $ref: '#/components/schemas/country_code'
        product_id:
          $ref: '#/components/schemas/id'
        pos_id:
          $ref: '#/components/schemas/id'
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: EUR
        transaction_data:
          transaction_id: a225edb0-0c03-11ed-ae03-c3d8f097c2ff
        country_code: BRA
        product_id: b7679b5c-0c02-11ed-8716-0b78014761cd
        pos_id: a225ed74-0c03-11ed-ae01-630c1a4b2fbc
    response-transactions:
      title: response-transactions
      description: ''
      type: object
      properties:
        transaction_id:
          type: string
        registered_at:
          format: date-time
          type: string
      example:
        transaction_id: a200609c-0c06-11ed-9205-73f6505a2b35
        registered_at: '2022-07-25T10:44:18+0000'
    generic-error:
      title: generic-error
      description: ''
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: '001'
        description: error message
    transaction-data-request:
      title: transaction-data-request
      description: ''
      type: object
      required:
        - operation
        - amount
        - transaction_id
        - card_id
      properties:
        with_password:
          type: boolean
        operation:
          type: string
          enum:
            - credit
            - debit
        amount:
          type: number
        transaction_id:
          $ref: '#/components/schemas/id'
        card_id:
          $ref: '#/components/schemas/id'
      example:
        with_password: true
        operation: credit
        amount: 231
        transaction_id: 172539e4-14aa-4030-921f-cefa228a37ed
        card_id : 172539e4-14aa-4030-921f-cefa228a37df
  responses:
    201-success:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response-transactions'
      description: ''
    400-bad-request:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    401-unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    403-forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    500-unavailable:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
tags:
  -
    name: transactions
    description: Transactions operations
